config/routes.rb
Rails.application.routes.draw do
  get 'tourspots/new'
  get 'tourspots/create'
  get 'tourspots/destroy'
  get 'tourspots/search1/:area', to: 'tourspots#search1', as:'search1'
  get 'spot/index'
  get 'spot/new'
  get 'spot/create'
  get 'spot/destroy'
  get 'spot/edit'
  get 'spot/show'
  get 'spot/search1'
  get 'spot/search2'
  get 'spot/search3'
  get 'spot/search4'
  get 'tour/index'
  get 'tour/new'
  get 'tour/create'
  get 'tour/destroy'
  get 'tour/search_guests1'
  get 'tour/search_guests2'
  get 'tour/search_guests3'
  # get 'reservation/index'
  # get 'reservation/new', to: 'reservations#new', as: :reservation_new
  # get 'reservation/create'
  # get 'reservation/edit'
  # get 'reservation/destroy'
  get 'reservations/record'
  get 'spots/index'
  get 'spots/show'
  get 'tourist/new'
  get 'tourist/create'
  get 'tourist/destroy'
  get 'tourist/show'
  get 'sessions/main'
  get 'sessions/login'
  get 'sessions/logout'
  get 'welcomes/index'
  root 'welcomes#index'
  post 'tourist/create'
  post 'sessions/login'
  post 'spot/create'
  post 'tour/create'
  post 'tourspots/create'
  post 'reservations/create'
  # post 'reservation/create'
  resources :spot
  resources :tourist
  resources :sessions
  resources :welcomes
  resources :reservations
  # resources :tourspots
  
  get 'reservation/:id', to: 'reservation#show'
  get 'reservations/:id', to: 'reservations#record'
  get 'get_spot/:id', to: 'spot#get_spot'

  get 'welcomes/fukuoka', to: 'welcomes#fukuoka'
  get 'welcomes/kitakyusyu', to: 'welcomes#kitakyusyu'
  get 'welcomes/chikuho', to: 'welcomes#chikuho'
  get 'welcomes/chikugo', to: 'welcomes#chikugo'

  get 'get_spot2/:id', to: 'spot#get_spot2'

  delete 'spot/:id', to: 'spot#destroy'
  get 'spot/:id', to: 'spot#show'
  get 'spot/:id/edit', to: 'spot#edit'
  patch 'spot/:id', to: 'spot#update'
  get 'tour/:id', to: 'tour#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_one :reservation
    # belongs_to :tourist
    # has_many :spots
    has_many :tourspots
    # has_many :tourspot_spots, through: :tourspots, source: :spot
    has_many :spots, through: :tourspots
end

app/controllers/tour_controller.rb
class TourController < ApplicationController
  def index
    @tour = Tour.all
  end

  def new
    @tour = Tour.new
  end

  def create
    @tour = Tour.new(name: params[:tour][:name],
    price: params[:tour][:price],
    area: params[:tour][:area],
    age: params[:tour][:age],
    number_of_people: params[:tour][:number_of_people],
    schedule: params[:tour][:schedule])
    if @tour.save
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    tour = Tour.find(params[:id])
    tour.destroy
    redirect_to root_path
  end
  
  def show
    Rails.logger.debug "params[:id]: #{params[:id]}"
    @tourspot = Tourspot.where(tour_id: params[:id])
    # @tour = Tour.find(params[:id])
  end
  
  def search_guests1
    @tour = Tour.all
  end
  
  def search_guests2
    @tour = Tour.all
  end
  
  def search_guests3
    @tour = Tour.all
  end
  
end

app/helpers/tour_helper.rb
module TourHelper
end

app/views/tour/create.html.erb
<h1>Tour#create</h1>
<p>Find me in app/views/tour/create.html.erb</p>

app/views/tour/destroy.html.erb
<h1>Tour#destroy</h1>
<p>Find me in app/views/tour/destroy.html.erb</p>

app/views/tour/index.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<h2>ツアー一覧</h2>

<div class="parent">
<% @tour.each do |e| %>
<div class="child">
    <strong><font face="ＭＳ 明朝"><%= e.name %></font></strong>
    <br>

    <% tourspot = Tourspot.find(e.id) %>
    <% spot = Spot.find(tourspot.spot_id) %>
    <%= "エリア:" %>
    <% if spot.area == 1 %>
        <%= "福岡エリア" %>
    <% elsif spot.area == 2 %>
        <%= "北九州エリア" %>
    <% elsif spot.area == 4 %>
        <%= "筑豊エリア" %>
    <% elsif spot.area == 3 %>
        <%= "筑後エリア" %>
    <% end %>

    <%= link_to '観光地を追加', tourspots_new_path(tour_id: e.id) %>
    <%= link_to 'ツアー詳細へ', "/tour/#{e.id}" %>
    <br>
    <br>
    </div>
<% end %>
</div>
<%= link_to "前ページに戻る" ,:back %>

app/views/tour/new.html.erb
<h1>※このページは開発者ページ！！！見えなくする！！</h1>
<%= form_for @tour , url: {action: :create} do |f| %>
<p><%= f.label :name, 'ツアー名' %>
<%= f.text_field :name %></p>
<p><%= f.label :price, '値段' %>
<%= f.number_field :price %></p>
<p><%= f.label :area, 'エリア(数字で入力! 1:福岡 2:北九州 3:筑後 4:筑豊)' %>
<%= f.number_field :area %></p>
<p><%= f.label :age, '年齢(数字で入力! 1:18歳未満 2:18-25歳 3:26-35歳 4:35-49歳 5:50歳以上)' %>
<%= f.number_field :age %></p>
<p><%= f.label :number_of_people, '人数(1:1人 2:2~5人 3:それ以上)' %>
<%= f.number_field :number_of_people %></p>
<p><%= f.label :schedule, 'タイムテーブル' %>
<%= f.text_field :schedule %></p>
<%= f.submit '登録' %>
<% end %>

<%= link_to "戻る" ,:back %>

app/views/tour/search_guests1.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<div class="parent">
<% @tour.each do |e| %>
<% if e.age == 1 %>
<div class="child">
    <% @tourspot = Tourspot.find(e.id) %>
    <% @spot = Spot.find(@tourspot.spot_id) %>
    <strong><font face="ＭＳ 明朝"><%= @spot.name %></font></strong>
    <br>
    <% if @spot.pictureinfo == 1 %>
    <%= image_tag "/get_spot/#{@spot.id}" , size: '300x200'%>
    <% elsif @spot.pictureinfo == 2 %>
    <%= image_tag "/get_spot/#{@spot.id}" , size: '225x300'%>
    <% end %>
    <br>

    <%= "エリア:" %>
    <% if @spot.area == 1 %>
        <%= "福岡エリア" %>
    <% elsif @spot.area == 2 %>
        <%= "北九州エリア" %>
    <% elsif @spot.area == 3 %>
        <%= "筑豊エリア" %>
    <% elsif @spot.area == 4 %>
        <%= "筑後エリア" %>
    <% end %>
    <%= "目的:" %>
    <% if @spot.purpose == 1 %>
        <%= "観光" %>
    <% elsif @spot.purpose == 2 %>
        <%= "グルメ" %>
    <% end %>
    <br>
    <%= @spot.address2 %>

    <%= link_to '観光地詳細へ', "/spot/#{@spot.id}" %>
    <br>


    <br>
    <br>
    </div>
<% end %>
<% end %>
</div>

<%= link_to "前ページに戻る" ,:back %>

app/views/tour/search_guests2.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<div class="parent">
<% @tour.each do |e| %>
<% if e.age == 2 %>
<div class="child">
    <% @tourspot = Tourspot.where(tour_id: e.id) %>
    <% @tourspot.each do |f| %>
    
    <% @spots = Spot.where(f.spot_id) %>
    <% @spots.each do |spot| %>
    <strong><font face="ＭＳ 明朝"><%= spot.name %></font></strong>
    <br>
    <% if spot.pictureinfo == 1 %>
    <%= image_tag "/get_spot/#{spot.id}" , size: '300x200'%>
    <% elsif spot.pictureinfo == 2 %>
    <%= image_tag "/get_spot/#{spot.id}" , size: '225x300'%>
    <% end %>
    <br>

    <%= "エリア:" %>
    <% if spot.area == 1 %>
        <%= "福岡エリア" %>
    <% elsif spot.area == 2 %>
        <%= "北九州エリア" %>
    <% elsif spot.area == 3 %>
        <%= "筑豊エリア" %>
    <% elsif spot.area == 4 %>
        <%= "筑後エリア" %>
    <% end %>
    <%= "目的:" %>
    <% if spot.purpose == 1 %>
        <%= "観光" %>
    <% elsif spot.purpose == 2 %>
        <%= "グルメ" %>
    <% end %>
    <br>
    <%= spot.address2 %>

    <%= link_to '観光地詳細へ', "/spot/#{spot.id}" %>
    <br>


    <br>
    <br>
    <% end %>
<% end %>
    </div>
<% end %>
<% end %>
</div>

<%= link_to "前ページに戻る" ,:back %>

app/views/tour/search_guests3.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<div class="parent">
<% @tour.each do |e| %>
<% if e.age == 3 %>
<div class="child">
    <% @tourspot = Tourspot.find(e.id) %>
    <% @spot = Spot.find(@tourspot.spot_id) %>
    <strong><font face="ＭＳ 明朝"><%= @spot.name %></font></strong>
    <br>
    <% if @spot.pictureinfo == 1 %>
    <%= image_tag "/get_spot/#{@spot.id}" , size: '300x200'%>
    <% elsif @spot.pictureinfo == 2 %>
    <%= image_tag "/get_spot/#{@spot.id}" , size: '225x300'%>
    <% end %>
    <br>

    <%= "エリア:" %>
    <% if @spot.area == 1 %>
        <%= "福岡エリア" %>
    <% elsif @spot.area == 2 %>
        <%= "北九州エリア" %>
    <% elsif @spot.area == 3 %>
        <%= "筑豊エリア" %>
    <% elsif @spot.area == 4 %>
        <%= "筑後エリア" %>
    <% end %>
    <%= "目的:" %>
    <% if @spot.purpose == 1 %>
        <%= "観光" %>
    <% elsif @spot.purpose == 2 %>
        <%= "グルメ" %>
    <% end %>
    <br>
    <%= @spot.address2 %>

    <%= link_to '観光地詳細へ', "/spot/#{@spot.id}" %>
    <br>


    <br>
    <br>
    </div>
<% end %>
<% end %>
</div>

<%= link_to "前ページに戻る" ,:back %>

app/views/tour/show.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<body bgcolor="#e6eae3">
<% tour = Tour.find(params[:id]) %>
<h1><font face="serif"><%= tour.name %></font></h1>
<br>

<strong><font color="#808000">観光先</font></strong>
<br>



<% @tourspot.each do |e| %>
    <% tour_spot = Spot.find(e.spot_id) %>
    <%= "・" %>


    <%= link_to tour_spot.name, "/spot/#{tour_spot.id}" %>
    <br>
<% end %>
<br>
<strong><font color="#808000">金額</font></strong>
<br>
<%= tour.price %>
<%= "円" %>
<br>
<br>
<strong><font color="#808000">タイムテーブル</font></strong>
<br>
<%= tour.schedule %>
<br>
<br>
<%= link_to 'ご予約へ', new_reservation_path(tour_id: tour.id, tourist_id: current_user.id) %>

<br>
<%= link_to '戻る', :back %>
<%= link_to 'トップへ', root_path %>
</body>