config/routes.rb
Rails.application.routes.draw do
  get 'tourspots/new'
  get 'tourspots/create'
  get 'tourspots/destroy'
  get 'tourspots/search1/:area', to: 'tourspots#search1', as:'search1'
  get 'spot/index'
  get 'spot/new'
  get 'spot/create'
  get 'spot/destroy'
  get 'spot/edit'
  get 'spot/show'
  get 'spot/search1'
  get 'spot/search2'
  get 'spot/search3'
  get 'spot/search4'
  get 'tour/index'
  get 'tour/new'
  get 'tour/create'
  get 'tour/destroy'
  get 'tour/search_guests1'
  get 'tour/search_guests2'
  get 'tour/search_guests3'
  # get 'reservation/index'
  # get 'reservation/new', to: 'reservations#new', as: :reservation_new
  # get 'reservation/create'
  # get 'reservation/edit'
  # get 'reservation/destroy'
  get 'reservations/record'
  get 'spots/index'
  get 'spots/show'
  get 'tourist/new'
  get 'tourist/create'
  get 'tourist/destroy'
  get 'tourist/show'
  get 'sessions/main'
  get 'sessions/login'
  get 'sessions/logout'
  get 'welcomes/index'
  root 'welcomes#index'
  post 'tourist/create'
  post 'sessions/login'
  post 'spot/create'
  post 'tour/create'
  post 'tourspots/create'
  post 'reservations/create'
  # post 'reservation/create'
  resources :spot
  resources :tourist
  resources :sessions
  resources :welcomes
  resources :reservations
  # resources :tourspots
  
  get 'reservation/:id', to: 'reservation#show'
  get 'reservations/:id', to: 'reservations#record'
  get 'get_spot/:id', to: 'spot#get_spot'

  get 'welcomes/fukuoka', to: 'welcomes#fukuoka'
  get 'welcomes/kitakyusyu', to: 'welcomes#kitakyusyu'
  get 'welcomes/chikuho', to: 'welcomes#chikuho'
  get 'welcomes/chikugo', to: 'welcomes#chikugo'

  get 'get_spot2/:id', to: 'spot#get_spot2'

  delete 'spot/:id', to: 'spot#destroy'
  get 'spot/:id', to: 'spot#show'
  get 'spot/:id/edit', to: 'spot#edit'
  patch 'spot/:id', to: 'spot#update'
  get 'tour/:id', to: 'tour#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/welcome.rb
class Welcome < ApplicationRecord
    has_many :tourists
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    @tourist = Tourist.all
  end
  
  def show
    render 'show'
  end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/fukuoka.html.erb
<h1>fukuoka</h1>

app/views/welcomes/index.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
<body>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<br>
<% if current_user %>
<nav>
  <ul>
  <li><%= link_to "マイページへ", tourist_show_path(id: current_user.id) %></li>
  <li style="float:right;"><%= link_to "ログアウト" ,sessions_logout_path %></li>
  <li><%= link_to "観光地追加" , spot_new_path %></li>
  <li><%= link_to "ツアー追加" , tour_new_path %></li>
  <li><%= link_to "観光地一覧", spot_index_path %></li>
  <li><%= link_to "ツアー一覧", tour_index_path %></li>
<% else %>
  <li><%= link_to "ログイン", sessions_main_path %></li>
<% end %>
  </ul>
</nav>


<!-- ↓新ハンバーガーメニュー↓ -->
	<div class="hamburger-demo-menubox">
		<input id="hamburger-demo1" type="checkbox" class="input-hidden">
		<label for="hamburger-demo1" class="hamburger-demo-switch hamburger-demo-switch1">
			<span class="hamburger-switch-line1"></span>
		</label>
		<div class="hamburger-demo-menuwrap">
			<ul class="hamburger-demo-menulist">
				<li><a href="#">マイページ</a></li>
				<li><a href="#">予約一覧</a></li>
				<li><a href="/L9/Fukuoka/tourist/create.html.erb">観光地検索</a></li>
				<li><a href="/L9/Fukuoka/tourist/create.html.erb">宿泊地検索</a></li>
				<li><a href="#">投稿</a></li>
			</ul>
		</div>
		<div class="hamburger-demo-cover"></div>
	</div>
<!-- ↑新ハンバーガーメニューここまで↑ -->
</div>


<!--<div>-->
<!--  <hr class="hr1">-->
<!--</div>-->

<hr>
<br>
<br>
<h4>エリアから検索する場合は地図をクリック！</h4>

<h5>人数検索</h5>
<%= link_to "1人", tour_search_guests1_path %>
<%= link_to "2~5人 ", tour_search_guests2_path%>
<%= link_to "それ以上", tour_search_guests3_path %>

<div class = 'map'>
    <%= image_tag 'map.png' %>

    <p id="chikugo"><a href="welcomes/chikugo" class="btn1">筑後</a></p>
    <p id="fukuoka"><a href="welcomes/fukuoka" class="btn2">福岡</a></p>
    <p id="kitakyusyu"><a href="welcomes/kitakyusyu" class="btn3">北九州</a></p>
    <p id="chikuho"><a href="welcomes/chikuho" class="btn4">筑豊</a></p>

    <!--<p id="chikugo"><a href="#" class="btn1">筑後</a></p>-->
    <%= link_to "筑後", spot_search3_path, id: "chikugo", class: "btn1" %>
    <%= link_to "福岡", spot_search1_path, id: "fukuoka", class: "btn2" %>
    <%= link_to "北九州", spot_search2_path, id: "kitakyusyu", class: "btn3" %>
    <%= link_to "筑豊", spot_search4_path, id: "chikuho", class: "btn4" %>
    <!--<p id="fukuoka"><a href="#" class="btn2">福岡</a></p>-->
    <!--<p id="kitakyusyu"><a href="#" class="btn3">北九州</a></p>-->
    <!--<p id="chikuho"><a href="#" class="btn4">筑豊</a></p>-->

</div>

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<form method="get" action="#" class="search_container">
  <input type="text" size="25" placeholder="　キーワード検索">
  <input type="submit" value="&#xf002">
</form>

<!--<div class="age">-->
<!--<select name="age">-->
<!--<option value="">年齢を選択してください</option>-->
<!--<option value="18歳未満">18歳未満</option>-->
<!--<option value="18-25歳">18-25歳</option>-->
<!--<option value="26-35歳">26-35歳</option>-->
<!--<option value="35-49歳">35-49歳</option>-->
<!--<option value="50歳以上">50歳以上</option>-->
<!--</select>-->
<!--</div>-->




<!--<div class="count">-->
<!--<select name="count">-->
<!--<option value="">人数を選択してください</option>-->
<!--<option value="18歳未満">1人</option>-->
<!--<option value="18-25歳">2人</option>-->
<!--<option value="26-35歳">3人</option>-->
<!--<option value="35-49歳">4人</option>-->
<!--<option value="50歳以上">5人以上</option>-->
<!--</select>-->
<!--</div>-->


<form>
  <lavel>
    <input type="date" />
  </label>
</form>
</body>

app/views/welcomes/show.html.erb
<!-- app/views/welcomes/show.html.erb -->
<%= link_to root_path, class: 'logo', method: :get do %>
<body>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>

<div class="hamburger-demo-menubox">
		<input id="hamburger-demo1" type="checkbox" class="input-hidden">
		<label for="hamburger-demo1" class="hamburger-demo-switch hamburger-demo-switch1">
			<span class="hamburger-switch-line1"></span>
		</label>
		<div class="hamburger-demo-menuwrap">
			<ul class="hamburger-demo-menulist">
				<li><a href="#">マイページ</a></li>
				<li><a href="#">予約一覧</a></li>
				<li><a href="/L9/Fukuoka/tourist/create.html.erb">観光地検索</a></li>
				<li><a href="/L9/Fukuoka/tourist/create.html.erb">宿泊地検索</a></li>
				<li><a href="#">投稿</a></li>
			</ul>
		</div>
		<div class="hamburger-demo-cover"></div>
	</div>

<div>
  <hr class="hr1">
</div>

<h1 id="fukkan">【福岡地方】おすすめ観光地＆グルメ　一覧！！！</h1>
<h2 id="kanko1">観光地</h2>
<ul1>
	<div class="flexbox">
		<article class = 'tower'>
			<%= image_tag 'fukuokatower.jpg', id:'tower_pic' %>
			<p>福岡タワー</p>
			<p>〒814-0001 福岡県福岡市早良区百道浜2丁目3-26</p>
		</articl>
		
		<articl class = 'BOSS'>
			<%= image_tag 'BOSS E･ZO FUKUOKA.jpg', id:'fuk_pic' %>
			<p>BOSS E･ZO FUKUOKA</p>
			<p>〒810-0065 福岡県福岡市中央区地行浜2丁目2-6</p>
		</articl>
		
		<articl class = 'paypay'>
			<%= image_tag 'paypay.jpg', id:'fuk_pic' %>
			<p>paypayドーム</p>
			<p>〒810-8660 福岡県福岡市中央区地行浜2丁目2-2</p>
		</articl>
		
		<div class = 'hakata'>
			<%= image_tag 'hakatastation.jpg', id:'fuk_pic' %>
			<p>JR博多駅</p>
			<p>〒812-0012福岡県福岡市博多区博多駅中央街1-1</p>
		</div>
		
		<articl class = 'lala'>
			<%= image_tag 'lala.jpg', id:'fuk_pic' %>
			<p>ららぽーと福岡</p>
			<p>〒812-8627福岡県福岡市博多区那珂6丁目23-1</p>
		</articl>
		
		<articl class = 'fukuma'>
			<%= image_tag 'fukuma3.jpg', id:'fuk_pic' %>
			<p>福間海岸</p>
			<p>〒811-3219福岡県福津市西福間3丁目</p>
		</articl>
		
		<articl class = 'shika'>
			<%= image_tag 'shikano.jpg', id:'fuk_pic' %>
			<p>志賀島</p>
			<p>〒811-0323福岡県福岡市東区志賀島1520-2</p>
		</articl>
		
		<articl class = 'dazaihu'>
			<%= image_tag 'dazaihu.jpg', id:'fuk_pic' %>
			<p>太宰府天満宮</p>
			<p>福岡県太宰府市宰府4丁目7番1号</p>
		</articl>
		
		<articl class = 'zoo'>
			<%= image_tag 'zoo.jpg', id:'fuk_pic' %>
			<p>福岡市動植物園</p>
			<p>〒810-0037福岡県福岡市南公園</p>
		</articl>
		
		<articl class = 'aqua'>
			<%= image_tag 'aqua.jpg', id:'fuk_pic' %>
			<p>マリンワールド海の中道</p>
			<p>〒811-0321福岡県福岡市東区大字西戸崎18-28</p>
		</articl>
		
		<articl class = 'miyaji'>
			<%= image_tag 'miyaji.jpg', id:'fuk_pic' %>
			<p>宮地嶽神社</p>
			<p>〒811-3309福岡県福津市宮司元町7-1</p>
		</articl>	
</ul1>
<ul2　class="flexbox">
	<h2 id="gurume">グルメ</h2>
	<div class="flexbox">
  	<article class="itiran">
    	<%= image_tag 'itiran2.jpg', id:'fuk_pic' %>
    	<p>一蘭 本社総本店</p>
    	<p>〒810-0801福岡県福岡市博多区中洲5丁目3-2</p>
  	</article>
	</div>
</ul2>