config/routes.rb
Rails.application.routes.draw do
  get 'tourspots/new'
  get 'tourspots/create'
  get 'tourspots/destroy'
  get 'tourspots/search1/:area', to: 'tourspots#search1', as:'search1'
  get 'spot/index'
  get 'spot/new'
  get 'spot/create'
  get 'spot/destroy'
  get 'spot/edit'
  get 'spot/show'
  get 'spot/search1'
  get 'spot/search2'
  get 'spot/search3'
  get 'spot/search4'
  get 'tour/index'
  get 'tour/new'
  get 'tour/create'
  get 'tour/destroy'
  get 'tour/search_guests1'
  get 'tour/search_guests2'
  get 'tour/search_guests3'
  # get 'reservation/index'
  # get 'reservation/new', to: 'reservations#new', as: :reservation_new
  # get 'reservation/create'
  # get 'reservation/edit'
  # get 'reservation/destroy'
  get 'reservations/record'
  get 'spots/index'
  get 'spots/show'
  get 'tourist/new'
  get 'tourist/create'
  get 'tourist/destroy'
  get 'tourist/show'
  get 'sessions/main'
  get 'sessions/login'
  get 'sessions/logout'
  get 'welcomes/index'
  root 'welcomes#index'
  post 'tourist/create'
  post 'sessions/login'
  post 'spot/create'
  post 'tour/create'
  post 'tourspots/create'
  post 'reservations/create'
  # post 'reservation/create'
  resources :spot
  resources :tourist
  resources :sessions
  resources :welcomes
  resources :reservations
  # resources :tourspots
  
  get 'reservation/:id', to: 'reservation#show'
  get 'reservations/:id', to: 'reservations#record'
  get 'get_spot/:id', to: 'spot#get_spot'

  get 'welcomes/fukuoka', to: 'welcomes#fukuoka'
  get 'welcomes/kitakyusyu', to: 'welcomes#kitakyusyu'
  get 'welcomes/chikuho', to: 'welcomes#chikuho'
  get 'welcomes/chikugo', to: 'welcomes#chikugo'

  get 'get_spot2/:id', to: 'spot#get_spot2'

  delete 'spot/:id', to: 'spot#destroy'
  get 'spot/:id', to: 'spot#show'
  get 'spot/:id/edit', to: 'spot#edit'
  patch 'spot/:id', to: 'spot#update'
  get 'tour/:id', to: 'tour#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tourist.rb
class Tourist < ApplicationRecord
    # belongs_to :welcome
    has_many :reservation
    # has_many :reservation_tours
    validates :password, presence: true, confirmation: true
    attr_accessor :password, :password_confirmation
    
    def password=(val)
        if val.present?
            self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
    
end

app/controllers/tourist_controller.rb
class TouristController < ApplicationController
  
  def new
    @tourist = Tourist.new
  end

  def create
    @tourist = Tourist.new(
      uid: params[:tourist][:uid],
      password: params[:tourist][:password],
      password_confirmation: params[:tourist][:password_confirmation])
    if @tourist.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    tourist = Tourist.find(params[:id])
    tourist.destroy
    redirect_to root_path
  end

  def show
    @tourist = Tourist.find(params[:id])
  end
end

app/helpers/tourist_helper.rb
module TouristHelper
end

app/views/tourist/create.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
<h1>Tourist#create</h1>
<p>Find me in app/views/tourist/create.html.erb</p>

app/views/tourist/destroy.html.erb
<h1>Tourist#destroy</h1>
<p>Find me in app/views/tourist/destroy.html.erb</p>

app/views/tourist/new.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>

<%= form_for @tourist, url: {action: :create} do |f| %>
<h3>新規会員登録</h3>
<p>
    <%= f.label :uid, "ユーザーID" %>
    <%= f.text_field :uid %>
</p>
<p>
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %>
</p>
<p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit '登録' %>
</p>
<% end %>

app/views/tourist/show.html.erb
<%= link_to root_path, class: 'logo', method: :get do %>
  <div>
    <%= image_tag "logo.png" %>
  </div>
<% end %>
<hr>


<link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">

<h3>
  <%= @tourist.uid %></h3>
  さんのマイページ
</srtong>
<br>
<br>

<%= link_to '予約一覧へ', reservations_record_path(tourist_id: @tourist.id) %>